from __future__ import annotations

from html import escape
from pathlib import Path
from typing import Any

from integral import integral_block


@integral_block(
    display_name="Dummy Vendor Report",
    description="Dummy vendor plugin から提供される外部 Python report block。",
    inputs=[],
    outputs=[
        {
            "name": "report",
            "extension": ".html",
            "datatype": "dummy-vendor/report-html",
            "auto_insert_to_work_note": True,
        }
    ],
    params={
        "type": "object",
        "properties": {
            "title": {
                "type": "string",
                "title": "Title",
                "default": "Dummy Vendor Report",
            },
            "value": {
                "type": "number",
                "title": "Demo value",
                "default": 42,
            },
        },
    },
)
def main(
    inputs: dict[str, str | None],
    outputs: dict[str, str | None],
    params: dict[str, Any] | None,
) -> None:
    del inputs
    effective_params = params or {}
    report_path = outputs.get("report") if outputs else None

    if not report_path:
        raise RuntimeError("report output path is required.")

    title = str(effective_params.get("title") or "Dummy Vendor Report")
    value = effective_params.get("value")
    Path(report_path).write_text(
        "\n".join(
            [
                "<!doctype html>",
                '<html lang="ja">',
                "<head>",
                '  <meta charset="UTF-8" />',
                f"  <title>{escape(title)}</title>",
                "</head>",
                "<body>",
                f"  <h1>{escape(title)}</h1>",
                f"  <p>Demo value: {escape(str(value))}</p>",
                "  <p>Generated by dummy-vendor external Python block.</p>",
                "</body>",
                "</html>",
            ]
        ),
        encoding="utf-8",
    )
