from __future__ import annotations

import html
import json
from pathlib import Path
from typing import Any

from integral import integral_block


@integral_block(
    display_name="Hello Report Demo",
    description="Generate a tiny HTML report without any input dataset.",
    outputs=["report"],
)
def main(
    inputs: dict[str, str | None],
    outputs: dict[str, str | None],
    params: dict[str, Any] | None,
) -> None:
    del inputs

    report_root = require_output_directory(outputs, "report")
    options = params or {}
    title = str(options.get("title") or "Hello Integral")
    message = str(options.get("message") or "This report was generated by the Integral Python SDK demo.")

    report_root.mkdir(parents=True, exist_ok=True)

    payload = {
        "title": title,
        "message": message,
        "generated_files": ["index.html", "payload.json", "README.txt"],
    }

    (report_root / "payload.json").write_text(
        json.dumps(payload, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    (report_root / "README.txt").write_text(
        f"{title}\n\n{message}\n",
        encoding="utf-8",
    )
    (report_root / "index.html").write_text(
        build_html(title=title, message=message),
        encoding="utf-8",
    )


def require_output_directory(values: dict[str, str | None], slot_name: str) -> Path:
    candidate = (values or {}).get(slot_name)

    if not candidate:
        raise ValueError(f"Output slot '{slot_name}' is required.")

    return Path(candidate)


def build_html(*, title: str, message: str) -> str:
    safe_title = html.escape(title)
    safe_message = html.escape(message)

    return f"""<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>{safe_title}</title>
    <style>
      body {{
        margin: 0;
        font-family: "Segoe UI", sans-serif;
        background: linear-gradient(135deg, #eef6ff, #f8fafc);
        color: #1f2937;
      }}

      main {{
        max-width: 720px;
        margin: 48px auto;
        padding: 32px;
        border: 1px solid #dbe4ee;
        border-radius: 20px;
        background: #ffffff;
        box-shadow: 0 14px 40px rgba(15, 23, 42, 0.08);
      }}

      p {{
        line-height: 1.7;
      }}

      code {{
        padding: 2px 8px;
        border-radius: 999px;
        background: #eff6ff;
        color: #1d4ed8;
      }}
    </style>
  </head>
  <body>
    <main>
      <p><code>scripts/demo_hello_report.py:main</code></p>
      <h1>{safe_title}</h1>
      <p>{safe_message}</p>
    </main>
  </body>
</html>
"""
